[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rocprof-trace-decoder"
version = "0.2.0"
description = "Python API for rocprof-trace-decoder"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Advanced Micro Devices, Inc." }]
dependencies = ["pyelftools>=0.31"]

[tool.setuptools]
package-dir = { "" = "python" }

[tool.setuptools.packages.find]
where = ["python"]
include = ["rocprof_trace_decoder*"]

[tool.ruff]
line-length = 100
